<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllCategories()
    {
        $em = $this->getEntityManager();
        $categories = $em->createQuery('SELECT c FROM AppBundle:Category c')->getResult();
        return $categories;
    }
}
