<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsByNoticeId($id)
    {
        $em = $this->getEntityManager();
        $comments = $em->createQuery('SELECT c FROM AppBundle:Comment c WHERE c.notice = :id')->setParameters(['id' => $id])->getResult();

        return $comments;
    }
}
