<?php

namespace AppBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Query\Expr\Join;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsByNoticeId($id)
    {
        $em = $this->getEntityManager();
        $comments = $em->createQuery('SELECT c FROM AppBundle:Comment c WHERE c.notice = :id')->setParameters(['id' => $id])->getResult();

        return $comments;
    }

    public function getCommentsByUserId($id)
    {
        $em = $this->getEntityManager();
//        $comments = $em->createQuery("SELECT c FROM AppBundle:Comment c join AppBundle:Notice n where n.user = :id")->setParameters(['id' => $id])->getResult();
//        $qb = $em->createQueryBuilder()->select('c')->from('AppBundle:Comment', 'c')->join('AppBundle:Notice', 'n')->where('n.user = :id')->setParameter('id',$id)->getQuery();
        $comments = $em->createQuery("SELECT c FROM AppBundle:Comment c WHERE c.user = :id")->setParameters(['id' => $id])->getResult();;
//        echo $qb->getDQL();
//        die;
//        $comments = $qb->getResult();
//        echo $qb->getDQL();
//        die;
        return $comments;
    }

//    public function getUsernameOfComment($commentId)
//    {
//        $em = $this->getEntityManager();
//        $username = $em->createQuery("SELECT ")
//    }
}
